---
- name: create tagged VG
  lvg:
    vg: "{{ item.name }}"
    pvs: "{{ item.pvs }}"
  notify:
    - deactivate VG
  register: vg_created
  with_items:
    - "{{ tagging_vgs }}"
  run_once: true

- name: create one LV on activated VG
  lvol:
    vg: "{{ item.0.name }}"
    lv: "{{ item.1.name }}"
    size: "{{ item.1.size }}"
    opts: --config "activation{volume_list=['{{ item.0.name }}']} global{locking_type=1}"
  with_subelements:
    - "{{ tagging_vgs }}"
    - lvs
  run_once: true
