---
- name: Disable use_lvmetad in /etc/lvm/lvm.conf if it exists
  lineinfile:
    dest: '/etc/lvm/lvm.conf'
    regexp: '^\s+use_lvmetad'
    line: '        use_lvmetad = 0'
  notify:
    - rebuild initramfs
    - rebuild initrd
  when: ansible_distribution_major_version in [ "6" ]

- name: Configure volume_list in /etc/lvm/lvm.conf
  lineinfile:
    dest: '/etc/lvm/lvm.conf'
    state: 'present'
    regexp: '^\s+volume_list\s*='
    line: "        volume_list = [ \"{{ [ root_vg ]|union(local_vg_list|default([]))|union(additional_volumes|default([]))|join('\",\"'|safe) }}\" ]"
    insertafter: '^activation {'
  notify:
    - rebuild initramfs
    - rebuild initrd
  when: ansible_distribution_major_version in [ "6" ] and HALVMtype == "tagging" or local_vg_list is defined

- name: Disable lvm2-lvmetad service
  service:
    name: 'lvm2-lvmetad'
    enabled: false
    state: 'stopped'
  ignore_errors: true
  # ignore failures as in the earlier version of EL6 the service didn't existed
  when: ansible_distribution_major_version in [ "6" ]

- name: Setup HA-LVM tagging
  include_tasks: ha-lvm-tagging.yml
  when: HALVMtype == "tagging"

- name: Setup HA-LVM CLVM
  include_tasks: ha-lvm-clvm.yml
  when: HALVMtype == "clvm"

- name: Configure tagging type VGs/LVs
  include_tasks: create_tagging_vgs_lvs.yml
  when: tagging_vgs is defined

- name: Configure clvm type VGs/LVs
  include_tasks: create_clvm_vgs_lvs.yml
  when: clvm_vgs is defined and HALVMtype == "clvm"
